/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CardWaterfallPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE = "card-waterfall-view";
var STATUS_OPTIONS = ["\u9ED8\u8BA4", "\u77ED\u7BC7", "\u957F\u7BC7", "\u5F52\u6863", "\u5176\u4ED6"];
var STATUS_COLORS = {
  "\u9ED8\u8BA4": "",
  "\u77ED\u7BC7": "#D4E2D4",
  "\u957F\u7BC7": "#D0D8E8",
  "\u5F52\u6863": "#D8D8D8",
  "\u5176\u4ED6": "#E8DCC8"
};
var STATUS_LABELS = {
  "\u9ED8\u8BA4": "\u9ED8\u8BA4",
  "\u77ED\u7BC7": "\u77ED\u7BC7",
  "\u957F\u7BC7": "\u957F\u7BC7",
  "\u5F52\u6863": "\u5F52\u6863",
  "\u5176\u4ED6": "\u5176\u4ED6"
};
var STATUS_BADGE_COLORS = {
  "\u9ED8\u8BA4": "",
  "\u77ED\u7BC7": "#5A8F5A",
  "\u957F\u7BC7": "#5A7FA8",
  "\u5F52\u6863": "#888888",
  "\u5176\u4ED6": "#A08060"
};
var DEFAULT_SETTINGS = {
  inspirationsFolder: "\u7075\u611F\u5361\u7247",
  cardColumns: 3
};
var TAG_DOT_COLORS = [
  "#FF6B6B",
  "#FFA94D",
  "#FFD43B",
  "#69DB7C",
  "#4DABF7",
  "#748FFC",
  "#DA77F2",
  "#F783AC",
  "#20C997",
  "#FF8787",
  "#A9E34B",
  "#339AF0",
  "#845EF7",
  "#E8590C",
  "#F06595"
];
function getTagColor(tag) {
  let hash = 0;
  for (let i = 0; i < tag.length; i++)
    hash = tag.charCodeAt(i) + ((hash << 5) - hash);
  return TAG_DOT_COLORS[Math.abs(hash) % TAG_DOT_COLORS.length];
}
function extractTitle(content) {
  const lines = content.split("\n").map((l) => l.trim()).filter((l) => l.length > 0);
  if (lines.length === 0)
    return "\u65E0\u6807\u9898";
  let title = lines[0];
  title = title.replace(/^#+\s+/, "");
  title = title.replace(/\*\*/g, "").replace(/\*/g, "");
  title = title.replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
  title = title.replace(/^(\p{Emoji_Presentation}|\p{Emoji}\uFE0F)+\s*/u, "");
  title = title.replace(/\p{Emoji_Presentation}|\p{Emoji}\uFE0F/gu, "");
  if (title.length > 16)
    title = title.slice(0, 16) + "\u2026";
  return title.trim() || "\u65E0\u6807\u9898";
}
function sanitizeFilename(name) {
  return name.replace(/[\\/:*?"<>|]/g, "_").replace(/\s+/g, " ").trim() || "\u672A\u547D\u540D";
}
var CardWaterfallPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE, (leaf) => new CardWaterfallView(leaf, this));
    this.addRibbonIcon("layers-3", "\u6253\u5F00\u7075\u611F\u5361\u7247\u7011\u5E03\u6D41", () => this.activateView());
    this.addCommand({ id: "open-card-waterfall", name: "\u6253\u5F00\u7075\u611F\u5361\u7247\u7011\u5E03\u6D41", callback: () => this.activateView() });
    this.addSettingTab(new CardWaterfallSettingTab(this.app, this));
    if (this.app.workspace.getLeavesOfType(VIEW_TYPE).length === 0)
      await this.activateView();
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE);
    if (leaves.length > 0)
      leaf = leaves[0];
    else {
      leaf = workspace.getRightLeaf(false);
      if (leaf)
        await leaf.setViewState({ type: VIEW_TYPE, active: true });
    }
    if (leaf)
      workspace.revealLeaf(leaf);
  }
  parseFrontmatter(content) {
    const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
    if (match) {
      try {
        return { frontmatter: (0, import_obsidian.parseYaml)(match[1]) || {}, body: match[2].trim() };
      } catch (e) {
        return { frontmatter: {}, body: content };
      }
    }
    return { frontmatter: {}, body: content.trim() };
  }
  async loadCards() {
    const folder = this.app.vault.getAbstractFileByPath(this.settings.inspirationsFolder);
    if (!folder)
      return [];
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(this.settings.inspirationsFolder + "/") && f.extension === "md");
    const cards = [];
    for (const file of files) {
      const raw = await this.app.vault.read(file);
      const { frontmatter, body } = this.parseFrontmatter(raw);
      const status = frontmatter.status || "\u9ED8\u8BA4";
      cards.push({
        id: file.basename,
        content: body || "(\u7A7A\u7075\u611F)",
        title: frontmatter.title || extractTitle(body || ""),
        created: frontmatter.created ? new Date(frontmatter.created).getTime() : file.stat.ctime,
        pinned: frontmatter.pinned === true,
        status: STATUS_OPTIONS.includes(status) ? status : "\u9ED8\u8BA4",
        tags: frontmatter.tags || [],
        file
      });
    }
    cards.sort((a, b) => {
      if (a.pinned && !b.pinned)
        return -1;
      if (!a.pinned && b.pinned)
        return 1;
      return b.created - a.created;
    });
    return cards;
  }
  async createCard(content, tags = []) {
    const now = new Date();
    const title = extractTitle(content);
    const safeName = sanitizeFilename(title);
    const pad2 = (n) => n.toString().padStart(2, "0");
    const tp = `${pad2(now.getMonth() + 1)}${pad2(now.getDate())}_${pad2(now.getHours())}${pad2(now.getMinutes())}`;
    const fp = `${this.settings.inspirationsFolder}/${tp}_${safeName}.md`;
    const f = this.app.vault.getAbstractFileByPath(this.settings.inspirationsFolder);
    if (!f)
      await this.app.vault.createFolder(this.settings.inspirationsFolder);
    await this.app.vault.create(fp, `---
${(0, import_obsidian.stringifyYaml)({ created: now.toISOString(), title, pinned: false, status: "\u9ED8\u8BA4", tags })}---

${content.trim()}
`);
    new import_obsidian.Notice("\u2705 \u7075\u611F\u5DF2\u8BB0\u5F55");
  }
  async setStatus(file, status) {
    const raw = await this.app.vault.read(file);
    const { frontmatter, body } = this.parseFrontmatter(raw);
    frontmatter.status = status;
    await this.app.vault.modify(file, `---
${(0, import_obsidian.stringifyYaml)(frontmatter)}---

${body}
`);
  }
  async togglePin(file) {
    const raw = await this.app.vault.read(file);
    const { frontmatter, body } = this.parseFrontmatter(raw);
    frontmatter.pinned = !frontmatter.pinned;
    await this.app.vault.modify(file, `---
${(0, import_obsidian.stringifyYaml)(frontmatter)}---

${body}
`);
  }
  async updateCardContent(file, newBody) {
    const raw = await this.app.vault.read(file);
    const { frontmatter } = this.parseFrontmatter(raw);
    frontmatter.title = extractTitle(newBody);
    await this.app.vault.modify(file, `---
${(0, import_obsidian.stringifyYaml)(frontmatter)}---

${newBody.trim()}
`);
  }
  async deleteCard(file) {
    await this.app.vault.delete(file);
    new import_obsidian.Notice("\u{1F5D1}\uFE0F \u7075\u611F\u5DF2\u5220\u9664");
  }
  async batchExport(files) {
    if (files.length === 0) {
      new import_obsidian.Notice("\u8BF7\u5148\u9009\u62E9\u8981\u5BFC\u51FA\u7684\u5361\u7247");
      return;
    }
    const lines = ["# \u7075\u611F\u5BFC\u51FA\n"];
    const sorted = [...files].sort((a, b) => a.stat.ctime - b.stat.ctime);
    for (const file of sorted) {
      const raw = await this.app.vault.read(file);
      const { frontmatter, body } = this.parseFrontmatter(raw);
      const date = frontmatter.created ? new Date(frontmatter.created).toLocaleString("zh-CN") : "\u672A\u77E5";
      lines.push(`## ${frontmatter.title || file.basename}`);
      lines.push(`> \u65F6\u95F4\uFF1A${date}`);
      if (frontmatter.pinned)
        lines.push("> \u{1F516} \u5DF2\u7F6E\u9876");
      lines.push("");
      lines.push(body);
      lines.push("");
      lines.push("---");
      lines.push("");
    }
    await this.app.vault.create(`\u7075\u611F\u5BFC\u51FA_${this.formatTimestamp(new Date())}.md`, lines.join("\n"));
    new import_obsidian.Notice(`\u2705 \u5DF2\u5BFC\u51FA ${files.length} \u6761\u7075\u611F`);
  }
  formatTimestamp(date) {
    const pad = (n) => n.toString().padStart(2, "0");
    return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}_${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`;
  }
};
var CardWaterfallView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.cards = [];
    this.selectedIds = /* @__PURE__ */ new Set();
    this.isSelectMode = false;
    this.searchQuery = "";
    this.statusFilter = "\u5168\u90E8";
    this.statusBtns = /* @__PURE__ */ new Map();
    this.cardElements = /* @__PURE__ */ new Map();
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "\u7075\u611F\u5361\u7247\u7011\u5E03\u6D41";
  }
  getIcon() {
    return "layers-3";
  }
  async onOpen() {
    this.buildUI();
    await this.refreshCards();
  }
  buildUI() {
    const c = this.containerEl;
    c.empty();
    c.addClass("card-waterfall-container");
    const tb = c.createDiv({ cls: "card-waterfall-topbar" });
    tb.createEl("h3", { text: "\u{1F4A1} \u7075\u611F\u7011\u5E03\u6D41", cls: "card-waterfall-title" });
    this.searchInputEl = tb.createEl("input", { type: "text", placeholder: "\u641C\u7D22\u7075\u611F...", cls: "card-waterfall-search" });
    this.searchInputEl.addEventListener("input", () => {
      this.searchQuery = this.searchInputEl.value;
      this.renderCards();
    });
    this.toolbarEl = tb.createDiv({ cls: "card-waterfall-toolbar" });
    const selectBtn = this.toolbarEl.createEl("button", { text: "\u9009\u62E9", cls: "card-waterfall-btn" });
    selectBtn.addEventListener("click", () => this.toggleSelectMode());
    const exportBtn = this.toolbarEl.createEl("button", { text: "\u5BFC\u51FA", cls: "card-waterfall-btn" });
    exportBtn.addEventListener("click", () => this.handleBatchExport());
    const refreshBtn = this.toolbarEl.createEl("button", { text: "\u5237\u65B0", cls: "card-waterfall-btn" });
    refreshBtn.addEventListener("click", () => this.refreshCards());
    this.statusBarEl = c.createDiv({ cls: "card-status-bar" });
    this.buildStatusFilter();
    this.gridEl = c.createDiv({ cls: "card-waterfall-grid" });
    this.emptyStateEl = c.createDiv({ cls: "card-waterfall-empty" });
    this.emptyStateEl.innerHTML = `<div class="empty-icon">\u2728</div><div class="empty-text">\u8FD8\u6CA1\u6709\u7075\u611F\uFF0C\u5199\u4E0B\u4F60\u7684\u7B2C\u4E00\u6761\u7075\u611F\u5427\uFF01</div>`;
    this.inputAreaEl = c.createDiv({ cls: "card-waterfall-input-area" });
    const tagRow = this.inputAreaEl.createDiv({ cls: "card-input-tag-row" });
    const tagInput = tagRow.createEl("input", { type: "text", placeholder: "\u6807\u7B7E\uFF08\u53EF\u9009\uFF0C\u9017\u53F7\u5206\u9694\uFF09", cls: "card-input-tags" });
    this.cardInputEl = this.inputAreaEl.createEl("textarea", { placeholder: "\u8BB0\u5F55\u4F60\u7684\u7075\u611F...\uFF08\u652F\u6301 Markdown \u683C\u5F0F\uFF09", cls: "card-waterfall-input", attr: { rows: "3" } });
    const submitBtn = this.inputAreaEl.createEl("button", { text: "\u53D1\u5E03\u7075\u611F \u{1F4A1}", cls: "card-waterfall-submit" });
    this.cardInputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.handleSubmit(tagInput);
      }
    });
    submitBtn.addEventListener("click", () => this.handleSubmit(tagInput));
    this.cardInputEl.addEventListener("input", () => {
      this.cardInputEl.style.height = "auto";
      this.cardInputEl.style.height = Math.min(this.cardInputEl.scrollHeight, 200) + "px";
    });
  }
  buildStatusFilter() {
    this.statusBarEl.empty();
    this.statusBtns.clear();
    const allBtn = this.statusBarEl.createEl("button", { text: "\u5168\u90E8", cls: "card-status-filter active" });
    allBtn.addEventListener("click", () => {
      this.statusFilter = "\u5168\u90E8";
      this.updateStatusFilterUI();
      this.renderCards();
    });
    this.statusBtns.set("\u5168\u90E8", allBtn);
    for (const s of STATUS_OPTIONS) {
      const btn = this.statusBarEl.createEl("button", { text: STATUS_LABELS[s], cls: "card-status-filter" });
      btn.addEventListener("click", () => {
        this.statusFilter = s;
        this.updateStatusFilterUI();
        this.renderCards();
      });
      this.statusBtns.set(s, btn);
    }
  }
  updateStatusFilterUI() {
    for (const [k, v] of this.statusBtns) {
      v.removeClass("active");
      if (k === this.statusFilter)
        v.addClass("active");
    }
  }
  async handleSubmit(tagInput) {
    const text = this.cardInputEl.value.trim();
    if (!text) {
      new import_obsidian.Notice("\u8BF7\u8F93\u5165\u7075\u611F\u5185\u5BB9");
      return;
    }
    const tags = tagInput.value.split(/[,，、\s]+/).map((t) => t.trim()).filter((t) => t.length > 0);
    await this.plugin.createCard(text, tags);
    this.cardInputEl.value = "";
    tagInput.value = "";
    this.cardInputEl.style.height = "auto";
    await this.refreshCards();
  }
  refreshCards() {
    this.plugin.loadCards().then((c) => {
      this.cards = c;
      this.renderCards();
    });
  }
  setCardStatus(card, newStatus) {
    this.plugin.setStatus(card.file, newStatus);
    card.status = newStatus;
    this.updateCardElement(card);
  }
  updateCardElement(card) {
    const el = this.cardElements.get(card.id);
    if (!el) {
      this.renderCards();
      return;
    }
    const bgColor = STATUS_COLORS[card.status] || null;
    if (bgColor) {
      el.style.backgroundColor = bgColor;
      el.style.borderColor = "transparent";
      el.style.opacity = card.status === "\u5F52\u6863" ? "0.7" : "";
    } else {
      el.style.backgroundColor = "";
      el.style.borderColor = "";
      el.style.opacity = "";
    }
    const oldBadge = el.querySelector(".card-status-badge");
    if (card.status !== "\u9ED8\u8BA4") {
      if (!oldBadge) {
        const titleEl = el.querySelector(".card-title");
        if (titleEl) {
          const stBadge = el.createDiv({ cls: "card-status-badge" });
          stBadge.textContent = STATUS_LABELS[card.status];
          stBadge.style.backgroundColor = "rgba(255,255,255,0.6)";
          stBadge.style.color = STATUS_BADGE_COLORS[card.status] || "#666";
          stBadge.style.border = "1px solid rgba(0,0,0,0.08)";
          titleEl.after(stBadge);
        }
      } else {
        oldBadge.textContent = STATUS_LABELS[card.status];
        oldBadge.style.color = STATUS_BADGE_COLORS[card.status] || "#666";
      }
    } else {
      if (oldBadge)
        oldBadge.remove();
    }
    const statusBtn = el.querySelector(".card-status-btn");
    if (statusBtn) {
      statusBtn.textContent = STATUS_LABELS[card.status];
      if (STATUS_BADGE_COLORS[card.status])
        statusBtn.style.color = STATUS_BADGE_COLORS[card.status];
      else
        statusBtn.style.color = "";
    }
  }
  renderCards() {
    this.gridEl.empty();
    const query = this.searchQuery.toLowerCase().trim();
    let filtered = this.cards;
    if (this.statusFilter !== "\u5168\u90E8") {
      filtered = filtered.filter((c) => c.status === this.statusFilter);
    }
    if (query) {
      filtered = filtered.filter(
        (c) => c.content.toLowerCase().includes(query) || c.title.toLowerCase().includes(query) || c.tags.some((t) => t.toLowerCase().includes(query))
      );
    }
    if (filtered.length === 0) {
      this.gridEl.style.display = "none";
      this.emptyStateEl.innerHTML = `<div class="empty-icon">\u{1F4ED}</div><div class="empty-text">\u6CA1\u6709\u5339\u914D\u7684\u7075\u611F</div>`;
      this.emptyStateEl.style.display = "flex";
      return;
    }
    this.gridEl.style.display = "";
    this.emptyStateEl.style.display = "none";
    this.cardElements.clear();
    for (const card of filtered) {
      const uniqueTags = [...new Set(card.tags)];
      const bgColor = STATUS_COLORS[card.status] || null;
      const cardEl = this.gridEl.createDiv({ cls: "card-waterfall-card", attr: { "data-id": card.id } });
      this.cardElements.set(card.id, cardEl);
      if (bgColor) {
        cardEl.style.backgroundColor = bgColor;
        cardEl.style.borderColor = "transparent";
      }
      if (card.status === "\u5F52\u6863") {
        cardEl.style.opacity = "0.7";
      }
      if (this.selectedIds.has(card.id))
        cardEl.addClass("is-selected");
      if (card.pinned)
        cardEl.addClass("is-pinned");
      cardEl.addEventListener("click", async () => {
        if (this.isSelectMode)
          return;
        const leaf = this.app.workspace.getLeaf(false);
        await leaf.openFile(card.file, { state: { mode: "source" } });
      });
      const header = cardEl.createDiv({ cls: "card-header" });
      if (card.pinned)
        header.createSpan({ text: "\u{1F4CC} \u5DF2\u7F6E\u9876", cls: "card-pin-badge" });
      if (uniqueTags.length > 0) {
        const tagDots = header.createSpan({ cls: "card-tag-dots" });
        for (const tag of uniqueTags) {
          const d = tagDots.createSpan({ cls: "card-tag-dot", attr: { title: tag } });
          d.style.backgroundColor = getTagColor(tag);
        }
      }
      header.createSpan({ cls: "card-time", text: this.formatDate(card.created) });
      const titleEl = cardEl.createDiv({ cls: "card-title" });
      titleEl.textContent = card.title;
      if (card.status !== "\u9ED8\u8BA4") {
        const stBadge = cardEl.createDiv({ cls: "card-status-badge" });
        stBadge.textContent = STATUS_LABELS[card.status];
        if (bgColor) {
          stBadge.style.backgroundColor = "rgba(255,255,255,0.6)";
          stBadge.style.color = STATUS_BADGE_COLORS[card.status] || "#666";
          stBadge.style.border = "1px solid rgba(0,0,0,0.08)";
        }
      }
      const body = cardEl.createDiv({ cls: "card-body" });
      let bodyContent = card.content.replace(/^#{1,3}\s+.*(\n|$)/, "").trim();
      const MAX_LEN = 500;
      let isTruncated = false;
      if (bodyContent.length > MAX_LEN) {
        bodyContent = bodyContent.slice(0, MAX_LEN);
        isTruncated = true;
      }
      import_obsidian.MarkdownRenderer.render(this.app, bodyContent || card.content, body, card.file.path, this.plugin);
      if (isTruncated)
        body.createEl("div", { cls: "card-expand-hint", text: "\u2026 \u70B9\u51FB\u5361\u7247\u5C55\u5F00\u67E5\u770B\u5B8C\u6574\u5185\u5BB9" });
      const actions = cardEl.createDiv({ cls: "card-actions" });
      if (this.isSelectMode) {
        const cb = actions.createEl("input", { type: "checkbox", cls: "card-checkbox" });
        cb.checked = this.selectedIds.has(card.id);
        cb.addEventListener("change", (e) => {
          e.stopPropagation();
          if (cb.checked) {
            this.selectedIds.add(card.id);
            cardEl.addClass("is-selected");
          } else {
            this.selectedIds.delete(card.id);
            cardEl.removeClass("is-selected");
          }
        });
      } else {
        const pinBtn = actions.createEl("button", { text: card.pinned ? "\u53D6\u6D88\u7F6E\u9876" : "\u7F6E\u9876", cls: "card-action-btn" });
        pinBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          await this.plugin.togglePin(card.file);
          await this.refreshCards();
        });
        const currentStatus = card.status;
        const statusBtn = actions.createEl("button", { text: STATUS_LABELS[currentStatus], cls: "card-action-btn card-status-btn" });
        if (STATUS_BADGE_COLORS[currentStatus])
          statusBtn.style.color = STATUS_BADGE_COLORS[currentStatus];
        statusBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          this.showStatusMenu(card, statusBtn);
        });
        const editBtn = actions.createEl("button", { text: "\u7F16\u8F91", cls: "card-action-btn" });
        editBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          await this.editCard(card);
        });
        const delBtn = actions.createEl("button", { text: "\u5220\u9664", cls: "card-action-btn card-action-danger" });
        delBtn.addEventListener("click", async (e) => {
          e.stopPropagation();
          if (confirm(`\u786E\u5B9A\u5220\u9664\u300C${card.title}\u300D\uFF1F`)) {
            await this.plugin.deleteCard(card.file);
            await this.refreshCards();
          }
        });
      }
    }
  }
  showStatusMenu(card, anchor) {
    document.querySelectorAll(".card-status-menu").forEach((el) => el.remove());
    const menu = anchor.createDiv({ cls: "card-status-menu" });
    menu.style.position = "absolute";
    menu.style.bottom = "100%";
    menu.style.left = "0";
    menu.style.zIndex = "100";
    menu.style.background = "var(--background-primary)";
    menu.style.border = "1px solid var(--background-modifier-border)";
    menu.style.borderRadius = "8px";
    menu.style.padding = "4px";
    menu.style.boxShadow = "0 4px 12px rgba(0,0,0,0.12)";
    menu.style.minWidth = "90px";
    for (const s of STATUS_OPTIONS) {
      const item = menu.createEl("button", { text: STATUS_LABELS[s], cls: "card-status-menu-item" });
      item.style.display = "block";
      item.style.width = "100%";
      item.style.padding = "6px 12px";
      item.style.border = "none";
      item.style.borderRadius = "4px";
      item.style.background = "transparent";
      item.style.cursor = "pointer";
      item.style.textAlign = "left";
      item.style.fontSize = "12px";
      if (STATUS_BADGE_COLORS[s])
        item.style.color = STATUS_BADGE_COLORS[s];
      if (s === card.status)
        item.style.fontWeight = "bold";
      item.addEventListener("mouseenter", () => {
        item.style.background = "var(--background-modifier-hover)";
      });
      item.addEventListener("mouseleave", () => {
        item.style.background = "transparent";
      });
      item.addEventListener("click", async (e) => {
        e.stopPropagation();
        card.status = s;
        await this.plugin.setStatus(card.file, s);
        this.updateCardElement(card);
        menu.remove();
      });
    }
  }
  async editCard(card) {
    const newContent = prompt("\u7F16\u8F91\u7075\u611F\u5185\u5BB9\uFF1A", card.content);
    if (newContent !== null && newContent.trim()) {
      await this.plugin.updateCardContent(card.file, newContent);
      await this.refreshCards();
      new import_obsidian.Notice("\u270F\uFE0F \u5DF2\u66F4\u65B0");
    }
  }
  toggleSelectMode() {
    this.isSelectMode = !this.isSelectMode;
    if (!this.isSelectMode) {
      this.selectedIds.clear();
      new import_obsidian.Notice("\u5DF2\u9000\u51FA\u9009\u62E9\u6A21\u5F0F");
    } else {
      new import_obsidian.Notice("\u52FE\u9009\u5361\u7247\u540E\u70B9\u51FB\u300C\u5BFC\u51FA\u300D\u6279\u91CF\u5BFC\u51FA");
    }
    this.renderCards();
  }
  async handleBatchExport() {
    if (!this.isSelectMode || this.selectedIds.size === 0) {
      this.isSelectMode = true;
      this.renderCards();
      new import_obsidian.Notice("\u8BF7\u5148\u52FE\u9009\u8981\u5BFC\u51FA\u7684\u5361\u7247");
      return;
    }
    const sf = this.cards.filter((c) => this.selectedIds.has(c.id)).map((c) => c.file);
    await this.plugin.batchExport(sf);
    this.isSelectMode = false;
    this.selectedIds.clear();
    this.renderCards();
  }
  formatDate(timestamp) {
    const d = new Date(timestamp);
    const pad = (n) => n.toString().padStart(2, "0");
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }
};
var CardWaterfallSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u7075\u611F\u5361\u7247\u7011\u5E03\u6D41 - \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u7075\u611F\u5361\u7247\u5B58\u50A8\u6587\u4EF6\u5939").setDesc("\u6BCF\u6761\u7075\u611F\u5C06\u4F5C\u4E3A\u5355\u72EC\u7684 Markdown \u6587\u4EF6\u5B58\u50A8\u5728\u6B64\u6587\u4EF6\u5939\u4E2D").addText((text) => text.setPlaceholder("\u7075\u611F\u5361\u7247").setValue(this.plugin.settings.inspirationsFolder).onChange(async (value) => {
      this.plugin.settings.inspirationsFolder = value || "\u7075\u611F\u5361\u7247";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u5361\u7247\u5217\u6570").setDesc("\u7011\u5E03\u6D41\u663E\u793A\u7684\u5217\u6570\uFF08\u684C\u9762\u7AEF\u63A8\u8350 3-4 \u5217\uFF09").addSlider((slider) => slider.setLimits(1, 6, 1).setValue(this.plugin.settings.cardColumns).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.cardColumns = value;
      await this.plugin.saveSettings();
      document.documentElement.style.setProperty("--card-waterfall-columns", value.toString());
    }));
  }
};
